### ISSUE TITLE
Mass collapsing

### ISSUE THREAD

**Issue by saghm** [PaulJuliusMartinez/jless#22]
Hello! I saw the HN post just now, and I happened to be working on a side project where I've been frequently using `jq` and `less` to reference the sample JSON I downloaded for an API I'm using (a frequent pattern of mine that I'm excited to find a new tool for!), and I realized that my preferred usage pattern some of the time would be to have everything start collapsed and then slowly expand fields as I need information about them. I'd love for there to be an option to start with all of the fields collapsed rather than expanded. Alternately (or as well), having a shortcut or command from within the viewer to collapse all of the fields would help me with this; I imagine it might even be reasonable to encode a larger swath of within-editor options as command line flags that just execute those commands when starting up (e.g. `jless --collapse-all --search "foo" bar.json`).

As an anecdotal point in favor of this sort of functionality, consider that most browser devtools will open the HTML inspector with the elements partially collapsed; even though this is likely due to the fact that the devtools pane will only take up a small part of the screen, it's still likely true that the JSON that this tool is most useful for will tend to be much longer than the number of lines the screen can show at once, as anything smaller than that could be just viewed entirely with `cat` (and maybe a pipe to something for syntax highlighting).

**Comment by cben** [comment]
Not 100% what you ask, but took me a while to discover so maybe I'm not the only one:  
`c`/`e` keys differ from `h`/`l`/←/→!  The latter collapse/expand current key, but `c`/`e` also collapse/expand *all siblings*.  

1. So, after launching jless press `c` and everything is collapsed.  (you'll see one root for json file, multiple for jsonlines or yaml with `---` document separators)  
2. Problem is, it's shallow collapse — expand any one and its whole depth gets revealed.
3. But, you can repeat this at each level: the key sequence `llc` (or `→→c`) will expand, move inside & collapse all entries, so "just" use that sequence to explore. :pick: 

No, this is not perfect, because when re-entering an object where _some_ sub-keys were previously expanded, the `c` stomps over that state.  So I don't advocate adding a key equivalent to `llc`.  Keys doing real recursive collapse / recursive expand would be better.

**Comment by ijoseph** [comment]
This is resolved as of 0.9.0 (https://github.com/PaulJuliusMartinez/jless/commit/5d5a597f6f4d8f6376a57cb9155f490a3e700fe6 in particular)

> Add C and E commands, analogous to the existing c and e commands, to deeply collapse/expand a node and all its siblings.

**Comment by ckjoris** [comment]
C and E commands are pretty great, however it doesn't solve the original posters request for CLI flag, so jless starts in collapsed mode
